### PR TITLE
Fix unknown type for SALZA2 compression.

### PR DESCRIPTION
**Pull request by phmarek**

### CODE REVIEW

**Comment by mbattyani** [comment]
Oops. Missed that one. Very good, thanks

**Comment by phmarek** [comment]
Sorry, just noticed that another commit went into the same PR as well - did you see that?

**Comment by mbattyani** [comment]
No. Which one?

**Comment by phmarek** [comment]
Your new `HEAD`, 24f8d30f0d2801b6c741c7579154475b09af7c58  ;)

**Comment by mbattyani** [comment]
I thought it was another contribution :)

**Pull request merged**
