### PR TITLE
Reworked lazy image loading to work for png files as well

### PR DESCRIPTION
**Pull request by lemaster**
Also added an example demonstrating how to activate the feature.

### CODE REVIEW

**Comment by mbattyani** [comment]
Very good. Thx!

**Comment by lemaster** [comment]
I was testing this on a different lisp system and it seems like the call to
add-dict-value in the initializer for pdf-stream needs to be changed to
change-dict-value to work. Although reading the code now, I am not sure why
it worked during my earlier tests. Maybe my old version of sbcl deferred
building the closure or something.

**Comment by mbattyani** [comment]
OK. BTW on which implementations have you tested it? I will test it on
Lispworks 6.1.

**Comment by lemaster** [comment]
I have tested it on SBCL 1.1.1.0 and SBCL 1.1.14
1.1.14 works with no changes.
1.1.1.0 requires the switch of add-dict-value to change-dict-value.

**Pull request merged**
